name: Validate With Schema
description: Action that validates json/yaml data against a given schema
inputs:
  schema-version:
    type: string
    required: true
    description: Version of the schema required, in SchemaVer
  schema-location:
    type: string
    required: true
    description: Directory within access-nri/schema that contains the schema
  data-location:
    type: string
    required: true
    description: Path(s) to the data file(s) in the callers repository
runs:
  using: composite
  steps:
    # Checkout the `schema-repo`
    - uses: actions/checkout@v4
      with:
        repository: access-nri/schema
        path: /opt/schema

    - shell: bash
      run: tree .

    - name: Check data extension
      shell: bash
      id: data
      run: |
        if [[ "${{ inputs.data-location }}" =~ \.ya?ml$ ]]; then
          echo "yaml=true" >> $GITHUB_OUTPUT
        else
          echo "yaml=false" >> $GITHUB_OUTPUT
        fi

    - uses: GrantBirki/json-yaml-validate@d7814b94473939c1daaca2c96131b891d4703a3c # v2.7.1
      with:
        mode: fail
        files: |
          ${{ inputs.data-location }}
        json_schema: /opt/schema/${{ inputs.schema-location }}/${{ inputs.schema-version }}.json
        yaml_as_json: ${{ steps.data.outputs.yaml }}
        ajv_strict_mode: false
        use_gitignore: false
