on:
  pull_request:
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: access-nri/actions/.github/actions/pr-comment@pr-comment-action
        with:
          comment: |
            a really cool comment!!
