on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  do-stuff:
    if: startsWith(github.event.comment.body, '!bump')
    runs-on: ubuntu-latest
    steps:
      - uses: access-nri/actions/.github/actions/react-to-comment@react-to-comment-action
        with:
          reaction: rocket

      - run: echo "WOW!!!!!!!!!!!!"