on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  do-stuff:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '!bump')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: access-nri/actions/.github/actions/react-to-comment@main
        with:
          reaction: rocket
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: access-nri/actions/.github/actions/pr-comment@pr-comment-action
        with:
          comment: |
            a really cool comment!!
