on:
  workflow_dispatch:
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: access-nri/build-cd/.github/actions/validate-repo-version@access-om3-2-generify-repo-check
        with:
          repos-to-check: spack-packages spack-config

      - uses: access-nri/build-cd/.github/actions/validate-repo-version@access-om3-2-generify-repo-check
        with:
          repos-to-check: spack-packages
