on:
  workflow_dispatch:
jobs:
  art-upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p some/other/dir
          touch some/other/dir/checksum1.txt
          touch some/other/dir/checksum2.txt

      - uses: actions/upload-artifact@v4
        with:
          name: arty
          path: ./some

  art-download:
    needs:
      - art-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: arty
          path: /opt/arts

      - run: ls -R /opt/arts


