on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building
        uses: access-nri/actions/.github/actions/docker-build-push@main
        with:
          container-registry: ghcr.io
          image-name: codegat-test-org/test-image
          dockerfile-name: Dockerfile.test
