on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/access-nri/build-access-om2-intel2021.2.0-2024.01.02:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: activate and install spack
        run: |
          . $SPACK_ROOT/share/spack/setup-env.sh
          spack env activate mom5
          spack -d install --add --only package --fail-fast --no-checksum mom5@git.master%intel@2021.2.0
          cd $SPACK_ROOT/var/spack/environments/mom5
          cp spack.lock mom5.original.spack.lock

      - name: See if mom5.original.spack.lock exists
        run: cat $SPACK_ROOT/var/spack/environments/mom5/mom5.original.spack.lock

      - name: Generate force-concretized lockfile
        if: failure()
        run: |
          . $SPACK_ROOT/share/spack/setup-env.sh
          cd $SPACK_ROOT/var/spack/environments/mom5
          spack -d concretize --force
          cp spack.lock mom5.force.spack.lock

      - name: Upload lockfiles
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: lockfile-output
          path: $SPACK_ROOT/var/spack/environments/mom5/mom5.*.spack.lock

