on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Building
        uses: access-nri/actions/.github/actions/docker-build-push@170-intermittent-push-fail
        with:
          container-registry: ghcr.io
          image-name: codegat-test-org/test-image-i-think
          dockerfile-name: Dockerfile.test
          push: true
