name: Matrix Dependent Jobs
on:
  workflow_dispatch:
jobs:
  j1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        x: [1, 2, 3]
    outputs:
      x-plus-one: ${{ steps.add.outputs.x-plus-one }}
    steps:
      - id: add
        run: echo "x-plus-one=$((${{ matrix.x }} + 1))" >> $GITHUB_OUTPUT

  j2:
    runs-on: ubuntu-latest
    needs:
      - j1
    steps:
      - run: echo ${{ needs.j1.outputs.x-plus-one }}
