name: env.yml
on:
  workflow_dispatch:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: payu

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: 3.11
          environment-file: conda/environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Run conda build
        shell: bash -el {0}
        env:
          GIT_DESCRIBE_TAG: test
          GIT_DESCRIBE_NUMBER: 0
        run: conda build . --no-anaconda-upload