name: env.yml
on:
  pull_request:
    paths:
      - 'env.yml'
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Payu Version String Exists
        run: |
          VERSION=$(yq eval '.dependencies[] | select(contains("accessnri::payu")) | split("==") | .[1]' env.yml)
          if [[ "$VERSION" == "null" ]]; then
            echo "::error::No Payu version string found in env.yml"
          fi

      - name: Env Valid
        uses: mamba-org/setup-micromamba@v1.7.0
        with:
          micromamba-version: '1.5.3-0'
          environment-file: env.yml
          environment-name: test-payu-environment
          generate-run-shell: true
