name: Schema
on:
  workflow_dispatch:
jobs:
  validate-with-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: access-nri/schema/.github/actions/validate-with-schema@add-validate-schema-action
        with:
          schema-location: au.org.access-nri/model/deployment/config/versions
          schema-version: 2-0-0
          data-location: config/versions.json

  validate-without-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: access-nri/schema/.github/actions/validate-with-schema@add-validate-schema-action
        with:
          schema-location: au.org.access-nri/model/deployment/config/versions
          schema-version: 2-0-0
          data-location: config/versions.json

  validate-with-correct-version:
    runs-on: ubuntu-latest
    steps:
      - uses: access-nri/schema/.github/actions/validate-with-schema@add-validate-schema-action
        with:
          schema-location: au.org.access-nri/model/deployment/config/versions
          schema-version: 1-0-0
          data-location: config/versions.json