name: Config Settings Deployment
on:
  workflow_call:
    inputs:
      deployment-environment:
        type: string
        required: true
        description: GitHub Deployment Environment Name
      spack-type:
        type: string
        required: true
        description: The type of spack deployment (eg. Prerelease, Release)
env:
  CONFIG_SETTINGS_PATH: ./config/settings.json
jobs:
  update-environment:
    name: Update ${{ inputs.deployment-environment }} ${{ inputs.spack-type }} Settings
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-environment }} ${{ inputs.spack-type }}
    steps:
      - run: |
          echo "${{ inputs.deployment-environment }} for ${{ inputs.spack-type }}"
          echo "${{ inputs.spack-update }}"
      # - name: Setup SSH
      #   id: ssh
      #   uses: access-nri/actions/.github/actions/setup-ssh@main
      #   with:
      #     hosts: ${{ secrets.HOST }}
      #     private-key: ${{ secrets.SSH_KEY }}

      - uses: actions/checkout@v4

      - name: Setup spack updates
        id: spack
        # TODO: Since we can't format this json as an input for this job (see the earlier workflow) we need to do it here
        run: |
          updates=$(jq --compact-output --raw-output \
            --arg env "${{ inputs.deployment-environment }}" \
            --arg type "${{ inputs.spack-type }}" \
            '.deployment[$env][$type].spack' \
            ${{ env.CONFIG_SETTINGS_PATH }}
          )
          versions=$(jq --null-input --compact-output --raw-output \
            --argjson vs "$updates" \
            '$vs | keys | @sh'
          )

          echo "$updates"
          echo "$versions"

          echo "updates=$updates" >> $GITHUB_OUTPUT
          echo "versions=$versions" >> $GITHUB_OUTPUT

      - name: Update
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for version in ${{ steps.spack.outputs.versions }}; do
            new_commit=$(jq --null-input --compact-output --raw-output \
              --arg v "$version" \
              --argjson vs "${{ steps.spack.outputs.updates }}" \
              '$vs[$v]'
            )

            # DEBUG
            gh repo clone access-nri/spack ./$version/spack -- -b releases/v$version

            current_head_commit=$(git -C ./$version/spack rev-parse HEAD)
            if [ $? -eq 128 ]; then
              echo "::error::Error: ${{ inputs.deployment-environment }} ${{ inputs.spack-type }} $version spack does not exist. Deploy it via build-cds Create Deployment Spack workflow first."
              continue
            fi

            git -C ./$version/spack fetch

            if [[ "$current_head_commit" != "$new_commit" ]]; then
              git -C ./$version/spack checkout $new_commit
              if [ $? -ne 0 ]; then
                echo "::error::Error: ${{ inputs.deployment-environment }} ${{ inputs.spack-type }} $version spack failed checkout from $current_head_commit to $new_commit"
              else
                echo "::notice::Changed: ${{ inputs.deployment-environment }} ${{ inputs.spack-type }} $version spack changed from $current_head_commit to $new_commit"
              fi
            else
              echo "::notice::Unchanged: ${{ inputs.deployment-environment }} ${{ inputs.spack-type }} $version spack left at $current_head_commit"
            fi
          done
