on:
  workflow_dispatch:
jobs:
  base-spack:
    runs-on: ubuntu-latest
    steps:
      - name: check
        id: no-image-exists
        run: echo "check=true" >> $GITHUB_OUTPUT
      - name: build
        if: steps.no-image-exists.outputs.check
        run: echo "Building base..."
  dependency-image:
    runs-on: ubuntu-latest
    needs:
      - base-spack
    steps:
      - name: build deps
        run: echo "Building deps..."
