name: spack to db
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Upload Metadata Artifact
      uses: actions/upload-artifact@v4
      with:
        name: thingy
        path: ./spack.*
        overwrite: true

  release:
    name: Create Release
    needs:
      - deploy
    runs-on: ubuntu-latest
    env:
      METADATA_PATH: /opt/metadata
    outputs:
      url: ${{ steps.release.outputs.url }}
      created-at: ${{ steps.metadata.outputs.created-at }}
    steps:
      - name: Download Metadata Artifact
        uses: actions/download-artifact@v4
        with:
          name: thingy
          path: ${{ env.METADATA_PATH }}

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: kool
          name: neat release
          body: wow!
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ${{ env.METADATA_PATH }}/spack.lock
            ${{ env.METADATA_PATH }}/spack.location.json

      - name: Release Metadata
        id: metadata
        env:
          GH_TOKEN: ${{ github.token }}
        run: echo "created-at=$(gh release view --json createdAt --jq '.createdAt')" >> $GITHUB_OUTPUT

  build-db:
    name: Build DB
    needs:
      - release
    runs-on: ubuntu-latest
    env:
      METADATA_PATH: /opt/metadata
    steps:
      - name: Download Metadata Artifact
        uses: actions/download-artifact@v4
        with:
          name: thingy
          path: ${{ env.METADATA_PATH }}

      - name: Checkout Upload Script
        uses: actions/checkout@v4
        with:
          repository: access-nri/build-cd

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Upload Build Metadata
        run: ./scripts/upload-build-metadata.bash ${{ needs.release.outputs.url }} ${{ needs.release.outputs.created-at }} ${{ env.METADATA_PATH }} access-om2 mom5 cice5 oasis3-mct libaccessom2
