on:
  workflow_dispatch:
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.KEY }}
      # - name: Add to known_hosts
      #   shell: bash
      #   env:
      #     HOST: ${{ secrets.HOST }}
      #   run: |
      #     ssh-keyscan ${{ env.HOST }} >> ~/.ssh/known_hosts
      #     chmod 600 ~/.ssh/known_hosts
      - name: ssh in
        run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} 'pwd'
