on:
  workflow_dispatch:
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: codegat-test-org/.github/actions/ssh-action@main
        id: ssh
        with:
          hosts: ${{ secrets.HOST }}
          private-key: ${{ secrets.KEY }}
      - run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          pwd
          EOT

