name: Test Settings Validation at PR Level
on:
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: access-nri/build-cd
          ref: 123-spack-config-in-settings-file

      - uses: access-nri/build-cd/.github/actions/validate-deployment-settings@123-spack-config-in-settings-file
        with:
          settings-path: ./config/settings.json
          target: Gadi
