name: Test Settings Validation at PR Level
on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  wowee:
    if: github.event. startsWith(github.event.comment.body, '!test')
    uses: ./.github/workflows/call.yml
    permissions:
      pull-requests: write
      contents: write
    secrets: inherit
