name: Test Expressions
on:
  workflow_dispatch:
    inputs:
      path1:
        type: string
        required: false
        default: .github/actions/settings/action.yml
      path2:
        type: string
        required: false
        default: .github/actions/validate/action.yml
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v7
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |-
            ${{ inputs.path1 }}
            ${{ inputs.path2 }}

      - name: Verify
        run: tree -a

      - name: Manifest - Delete History
        # Specifically, this is to avoid exposing a private spack manifest repository's history to the actor if they SSH in
        if: always() && steps.checkout.conclusion == 'success'
        run: rm -rf ./.git

      - name: Verify post-removal
        run: tree -a
