name: Test Expressions
on:
  workflow_dispatch:
    inputs:
      run-self-hosted:
        type: boolean
        default: true
jobs:
  spack-install-and-test:
    name: Install and Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/access-nri/build-ci-runner:rocky-v0.22
      volumes:
        # For self-hosted runners, mount the proper upstream and buildcache volumes from the kubernetes cluster
        # For GitHub-hosted runners, mount the upstream but add a dummy buildcache volume /dev/null to avoid errors or undefined behavior, eg. fromJson('[]')
        - ${{ inputs.run-self-hosted && '/opt/upstream:/opt/upstream:ro' || 'upstream-data:/opt/upstream:ro' }}
        - ${{ inputs.run-self-hosted && '/opt/runner_set_buildcache:/opt/runner_set_buildcache:rw' || '/dev/null:/dev/null:ro' }}
    services:
      upstream:
        image: ${{ ! inputs.run-self-hosted && 'ghcr.io/access-nri/build-ci-upstream:rocky-v0.22' || '' }}
        volumes:
        - upstream-data:/opt/upstream:rw
    steps:
    - run: ls -alh /opt/upstream
