name: Test Settings Validation at PR Level
on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  wowee:
    if: startsWith(github.event.comment.body, '!test')
    uses: codegat-test-org/test/.github/workflows/call.yml@main
    permissions:
      pull-requests: write
      contents: write
      checks: write
    secrets: inherit
