name: Version Bump Test
on:
  workflow_dispatch:
jobs:
  bump-things:
    runs-on: ubuntu-latest
    steps:
      - id: bump-cal-minor
        uses: codegat-test-org/actions/.github/actions/bump-version@main
        with:
          version: 2024.01.2
          versioning-scheme: calver-minor
          bump-type: minor

      - id: bump-cal-major
        uses: codegat-test-org/actions/.github/actions/bump-version@main
        with:
          version: 2024.01.2
          versioning-scheme: calver-minor
          bump-type: major

      - id: bump-cal-current
        uses: codegat-test-org/actions/.github/actions/bump-version@main
        with:
          version: 2024.01.2
          versioning-scheme: calver-minor
          bump-type: current

      - id: bump-sem-minor
        uses: codegat-test-org/actions/.github/actions/bump-version@main
        with:
          version: 12.33
          versioning-scheme: semver-major-minor
          bump-type: minor

      - id: bump-sem-major
        uses: codegat-test-org/actions/.github/actions/bump-version@main
        with:
          version: 12.33
          versioning-scheme: semver-major-minor
          bump-type: major

      - if: always()
        run: |
          echo "${{ steps.bump-cal-minor.outputs.before }}"
          echo " calver minor bump: ${{ steps.bump-cal-minor.outputs.after }}"
          echo "${{ steps.bump-cal-minor.outputs.type }}"

          echo "calver major bump: ${{ steps.bump-cal-major.outputs.after }}"
          echo "calver current bump: ${{ steps.bump-cal-current.outputs.after }}"

          echo "${{ steps.bump-sem-minor.outputs.after }}"

          echo "${{ steps.bump-sem-major.outputs.after }}"
